/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */

export type AuthorizeParams = {
/**
 * The client ID issued to the client during the registration process.
 */
client_id: string;
/**
 * The redirect URI to which the response will be sent.
 */
redirect_uri: string;
/**
 * Code challenge used for PKCE flow.
 */
code_challenge?: string;
/**
 * Method used to generate the code challenge.
 */
code_challenge_method?: string;
/**
 * Opaque value used to maintain state between the request and the callback.
 */
state?: string;
/**
 * Space-separated list of scopes the client is requesting.
 */
scope?: string;
/**
 * The type of response desired. Typically "code" for Authorization Code Flow.
 */
response_type?: string;
};
