/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */
import type { CreateUserResponseData } from './createUserResponseData';

export interface CreateUserResponse {
  successMessage: string;
  data?: CreateUserResponseData;
}
