/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */
import type { CreateUserRequestRole } from './createUserRequestRole';

export interface CreateUserRequest {
  /** First name of the user */
  firstName: string;
  /** Last name of the user */
  lastName?: string;
  /** User email address */
  email: string;
  /** User phone number */
  phoneNumber?: string;
  /** Unique username */
  username: string;
  /** User password */
  password?: string;
  /** Role of the user */
  role?: CreateUserRequestRole;
}
