/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */

/**
 * Role of the user
 */
export type CreateUserRequestRole = typeof CreateUserRequestRole[keyof typeof CreateUserRequestRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserRequestRole = {
  MEMBER: 'MEMBER',
  MODRATOR: 'MODRATOR',
  DEV: 'DEV',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;
