/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */
import type { CreateUserResponseDataId } from './createUserResponseDataId';
import type { CreateUserResponseDataFirstName } from './createUserResponseDataFirstName';
import type { CreateUserResponseDataLastName } from './createUserResponseDataLastName';
import type { CreateUserResponseDataEmail } from './createUserResponseDataEmail';
import type { CreateUserResponseDataPhoneNumber } from './createUserResponseDataPhoneNumber';
import type { CreateUserResponseDataRole } from './createUserResponseDataRole';

export interface CreateUserResponseData {
  id?: CreateUserResponseDataId;
  firstName?: CreateUserResponseDataFirstName;
  lastName?: CreateUserResponseDataLastName;
  email?: CreateUserResponseDataEmail;
  phoneNumber?: CreateUserResponseDataPhoneNumber;
  role?: CreateUserResponseDataRole;
}
