/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */
import type { GetUserResponseDataId } from './getUserResponseDataId';
import type { GetUserResponseDataFirstName } from './getUserResponseDataFirstName';
import type { GetUserResponseDataLastName } from './getUserResponseDataLastName';
import type { GetUserResponseDataEmail } from './getUserResponseDataEmail';
import type { GetUserResponseDataPhoneNumber } from './getUserResponseDataPhoneNumber';
import type { GetUserResponseDataUsername } from './getUserResponseDataUsername';
import type { GetUserResponseDataRole } from './getUserResponseDataRole';
import type { GetUserResponseDataIsActive } from './getUserResponseDataIsActive';
import type { GetUserResponseDataCreatedAt } from './getUserResponseDataCreatedAt';

export interface GetUserResponseData {
  /** User ID */
  id: GetUserResponseDataId;
  /** First name of the user */
  firstName: GetUserResponseDataFirstName;
  /** Last name of the user */
  lastName: GetUserResponseDataLastName;
  /** Email of the user */
  email: GetUserResponseDataEmail;
  /** Phone number of the user */
  phoneNumber?: GetUserResponseDataPhoneNumber;
  /** Username of the user */
  username: GetUserResponseDataUsername;
  /** Role of the user */
  role: GetUserResponseDataRole;
  /** Whether the user is active */
  isActive: GetUserResponseDataIsActive;
  /** User creation timestamp */
  createdAt: GetUserResponseDataCreatedAt;
}
