/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */
import type { GetUserSelfResponseDataId } from './getUserSelfResponseDataId';
import type { GetUserSelfResponseDataFirstName } from './getUserSelfResponseDataFirstName';
import type { GetUserSelfResponseDataLastName } from './getUserSelfResponseDataLastName';
import type { GetUserSelfResponseDataEmail } from './getUserSelfResponseDataEmail';
import type { GetUserSelfResponseDataPhoneNumber } from './getUserSelfResponseDataPhoneNumber';
import type { GetUserSelfResponseDataUsername } from './getUserSelfResponseDataUsername';
import type { GetUserSelfResponseDataRole } from './getUserSelfResponseDataRole';
import type { GetUserSelfResponseDataIsActive } from './getUserSelfResponseDataIsActive';
import type { GetUserSelfResponseDataCreatedAt } from './getUserSelfResponseDataCreatedAt';

export interface GetUserSelfResponseData {
  /** User ID */
  id: GetUserSelfResponseDataId;
  /** First name of the user */
  firstName: GetUserSelfResponseDataFirstName;
  /** Last name of the user */
  lastName: GetUserSelfResponseDataLastName;
  /** Email of the user */
  email: GetUserSelfResponseDataEmail;
  /** Phone number of the user */
  phoneNumber?: GetUserSelfResponseDataPhoneNumber;
  /** Username of the user */
  username: GetUserSelfResponseDataUsername;
  /** Role of the user */
  role: GetUserSelfResponseDataRole;
  /** Whether the user is active */
  isActive: GetUserSelfResponseDataIsActive;
  /** User creation timestamp */
  createdAt: GetUserSelfResponseDataCreatedAt;
}
