/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */

/**
 * Phone number of the user
 */
export type GetUserSelfResponseDataPhoneNumber = { [key: string]: unknown };
