/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */

/**
 * Whether the user is active
 */
export type GetUserResponseDataIsActive = { [key: string]: unknown };
