/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */
import type { JwksItem } from './jwksItem';

export interface JwksResponse {
  /** Array of JSON Web Keys */
  keys: JwksItem[];
}
