/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */

export interface LoginRequest {
  /** The username for the login request */
  username: string;
  /** The password for the login request */
  password: string;
  /** The client ID associated with the login request */
  clientId: string;
  /** The redirect URI after login */
  redirectUri: string;
  /** The code challenge for the login request */
  codeChallenge: string;
  /** The method used to generate the code challenge */
  codeChallengeMethod: string;
  /** Optional state parameter to maintain state between the request and callback */
  state?: string;
}
