/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * API
 * 
  <h3>📌 Welcome to the <strong>IAM</strong> 🚀</h3>
  
 * OpenAPI spec version: 1.0
 */

export interface UserInfoResponse {
  /** Subject Identifier - unique user ID */
  sub: string;
  /** Full name of the user */
  name: string;
  /** Preferred username */
  preferred_username: string;
  /** Email address of the user */
  email: string;
}
