version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    command: sleep infinity

    networks:
      - my-network

    ports:
      - "3000:3000"

networks:
  my-network:
    driver: bridge


    # network_mode: service:db

#   db:
#     image: postgres:latest
#     restart: unless-stopped
#     volumes:
#       - postgres-data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_DB: sample

#   pgadmin:
#     image: dpage/pgadmin4
#     ports:
#       - "5050:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: local@local.com
#       PGADMIN_DEFAULT_PASSWORD: computer
#     volumes:
#       - pgadmin-data:/var/lib/pgadmin
#     depends_on:
#       - db

# volumes:
#   pgadmin-data:
#   postgres-data: